// DO NOT EDIT. generated by webtyp.com/ormc

package rbac

import (
	"webtyp.com/model"
	"webtyp.com/orm"
)

type Role struct {
	ProjectId string
	Id string
	Code string
	Name string
	Description string
	SessionTtl int64
}

func (m *Role) ModelName() string { return "role" }

func (m *Role) Schema() []model.Field { return RoleModel.Fields }

func (m *Role) Pointers() []any { return []any{&m.ProjectId, &m.Id, &m.Code, &m.Name, &m.Description, &m.SessionTtl} }

func (m *Role) IsNil() bool { return m == nil }

func (m *Role) EncodeFields(w model.FieldWriter) {
	w.String("project_id", m.ProjectId)
	w.String("id", m.Id)
	w.String("code", m.Code)
	w.String("name", m.Name)
	w.String("description", m.Description)
	w.Int("session_ttl", m.SessionTtl)
}

func (m *Role) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("project_id"); ok { m.ProjectId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("code"); ok { m.Code = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("description"); ok { m.Description = v }
	if v, ok := r.Int("session_ttl"); ok { m.SessionTtl = v }
}

type RoleList []*Role

func (s *RoleList) Len() int             { return len(*s) }
func (s *RoleList) At(i int) model.Fielder { return (*s)[i] }
func (s *RoleList) Append() model.Fielder  { v := &Role{}; *s = append(*s, v); return v }
func (s *RoleList) IsNil() bool          { return s == nil }
func (s *RoleList) EncodeFields(_ model.FieldWriter) {}
func (s *RoleList) DecodeFields(_ model.FieldReader) {}

func (m *Role) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Role_ = struct {
	ProjectId string
	Id string
	Code string
	Name string
	Description string
	SessionTtl string
}{
	ProjectId: "project_id",
	Id: "id",
	Code: "code",
	Name: "name",
	Description: "description",
	SessionTtl: "session_ttl",
}

func ReadOneRole(qb *orm.QB, model *Role) (*Role, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRole(qb *orm.QB) (RoleList, error) {
	var results RoleList
	err := qb.ReadAll(
		func() model.Model { return &Role{} },
		func(m model.Model) { results = append(results, m.(*Role)) },
	)
	return results, err
}

type Permission struct {
	ProjectId string
	Id string
	Name string
	Resource string
	Action string
}

func (m *Permission) ModelName() string { return "permission" }

func (m *Permission) Schema() []model.Field { return PermissionModel.Fields }

func (m *Permission) Pointers() []any { return []any{&m.ProjectId, &m.Id, &m.Name, &m.Resource, &m.Action} }

func (m *Permission) IsNil() bool { return m == nil }

func (m *Permission) EncodeFields(w model.FieldWriter) {
	w.String("project_id", m.ProjectId)
	w.String("id", m.Id)
	w.String("name", m.Name)
	w.String("resource", m.Resource)
	w.String("action", m.Action)
}

func (m *Permission) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("project_id"); ok { m.ProjectId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("resource"); ok { m.Resource = v }
	if v, ok := r.String("action"); ok { m.Action = v }
}

type PermissionList []*Permission

func (s *PermissionList) Len() int             { return len(*s) }
func (s *PermissionList) At(i int) model.Fielder { return (*s)[i] }
func (s *PermissionList) Append() model.Fielder  { v := &Permission{}; *s = append(*s, v); return v }
func (s *PermissionList) IsNil() bool          { return s == nil }
func (s *PermissionList) EncodeFields(_ model.FieldWriter) {}
func (s *PermissionList) DecodeFields(_ model.FieldReader) {}

func (m *Permission) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Permission_ = struct {
	ProjectId string
	Id string
	Name string
	Resource string
	Action string
}{
	ProjectId: "project_id",
	Id: "id",
	Name: "name",
	Resource: "resource",
	Action: "action",
}

func ReadOnePermission(qb *orm.QB, model *Permission) (*Permission, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllPermission(qb *orm.QB) (PermissionList, error) {
	var results PermissionList
	err := qb.ReadAll(
		func() model.Model { return &Permission{} },
		func(m model.Model) { results = append(results, m.(*Permission)) },
	)
	return results, err
}

type UserRole struct {
	ProjectId string
	UserId string
	RoleId string
}

func (m *UserRole) ModelName() string { return "user_role" }

func (m *UserRole) Schema() []model.Field { return UserRoleModel.Fields }

func (m *UserRole) Pointers() []any { return []any{&m.ProjectId, &m.UserId, &m.RoleId} }

func (m *UserRole) IsNil() bool { return m == nil }

func (m *UserRole) EncodeFields(w model.FieldWriter) {
	w.String("project_id", m.ProjectId)
	w.String("user_id", m.UserId)
	w.String("role_id", m.RoleId)
}

func (m *UserRole) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("project_id"); ok { m.ProjectId = v }
	if v, ok := r.String("user_id"); ok { m.UserId = v }
	if v, ok := r.String("role_id"); ok { m.RoleId = v }
}

type UserRoleList []*UserRole

func (s *UserRoleList) Len() int             { return len(*s) }
func (s *UserRoleList) At(i int) model.Fielder { return (*s)[i] }
func (s *UserRoleList) Append() model.Fielder  { v := &UserRole{}; *s = append(*s, v); return v }
func (s *UserRoleList) IsNil() bool          { return s == nil }
func (s *UserRoleList) EncodeFields(_ model.FieldWriter) {}
func (s *UserRoleList) DecodeFields(_ model.FieldReader) {}

func (m *UserRole) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var UserRole_ = struct {
	ProjectId string
	UserId string
	RoleId string
}{
	ProjectId: "project_id",
	UserId: "user_id",
	RoleId: "role_id",
}

func ReadOneUserRole(qb *orm.QB, model *UserRole) (*UserRole, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllUserRole(qb *orm.QB) (UserRoleList, error) {
	var results UserRoleList
	err := qb.ReadAll(
		func() model.Model { return &UserRole{} },
		func(m model.Model) { results = append(results, m.(*UserRole)) },
	)
	return results, err
}

type RolePermission struct {
	ProjectId string
	RoleId string
	PermissionId string
}

func (m *RolePermission) ModelName() string { return "role_permission" }

func (m *RolePermission) Schema() []model.Field { return RolePermissionModel.Fields }

func (m *RolePermission) Pointers() []any { return []any{&m.ProjectId, &m.RoleId, &m.PermissionId} }

func (m *RolePermission) IsNil() bool { return m == nil }

func (m *RolePermission) EncodeFields(w model.FieldWriter) {
	w.String("project_id", m.ProjectId)
	w.String("role_id", m.RoleId)
	w.String("permission_id", m.PermissionId)
}

func (m *RolePermission) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("project_id"); ok { m.ProjectId = v }
	if v, ok := r.String("role_id"); ok { m.RoleId = v }
	if v, ok := r.String("permission_id"); ok { m.PermissionId = v }
}

type RolePermissionList []*RolePermission

func (s *RolePermissionList) Len() int             { return len(*s) }
func (s *RolePermissionList) At(i int) model.Fielder { return (*s)[i] }
func (s *RolePermissionList) Append() model.Fielder  { v := &RolePermission{}; *s = append(*s, v); return v }
func (s *RolePermissionList) IsNil() bool          { return s == nil }
func (s *RolePermissionList) EncodeFields(_ model.FieldWriter) {}
func (s *RolePermissionList) DecodeFields(_ model.FieldReader) {}

func (m *RolePermission) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var RolePermission_ = struct {
	ProjectId string
	RoleId string
	PermissionId string
}{
	ProjectId: "project_id",
	RoleId: "role_id",
	PermissionId: "permission_id",
}

func ReadOneRolePermission(qb *orm.QB, model *RolePermission) (*RolePermission, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRolePermission(qb *orm.QB) (RolePermissionList, error) {
	var results RolePermissionList
	err := qb.ReadAll(
		func() model.Model { return &RolePermission{} },
		func(m model.Model) { results = append(results, m.(*RolePermission)) },
	)
	return results, err
}

